# Generated by Django 4.2.7 on 2023-11-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default='product.png', null=True, upload_to='product_img/'),
        ),
    ]
